### ISSUE TITLE
请问主页站点是被劫持了吗？跳转的是一个叫sen.js的路由

### ISSUE THREAD

**Issue by DawnSouther** [hana-group/hana-ui#14]
![image](https://user-images.githubusercontent.com/22205542/81502150-c8729880-930e-11ea-9aab-05b365a232c3.png)

**Comment by dtysky** [comment]
奇怪了。。。我这没问题啊，虽然现在这两个网站是放在一个服务器上的。

**Comment by DawnSouther** [comment]
我又试了一下，看起来像是https重定向的问题，直接使用http没问题
