### ISSUE TITLE
移植angular版本的hana-ui

### ISSUE THREAD

**Issue by DawnSouther** [hana-group/hana-ui#15]
Hi @dtysky ，
    我是一名hana-ui的老二次元使用者。
    我关注这个项目三年了，非常喜欢hana的风格。
    因为一直主职是后端，对前端不是特别精通，所以对hana一直是在远观的程度XD。之后因为一些原因我了解到angular，深入研究后对它工程化的思想非常喜欢。
    那么长话短说，我想要构建一个ui库。恰好hana非常对我的胃口，同时我也不想hana这个非常精致、清新的ui最后落个不再维护的结局。
    我目前已经开始了移植hana，移植的过程中我发现不仅要做组件的移植，还要构建测试用例及制作doc站点。工作量太过巨大，我一个人的力量实在是太渺小。所以想请求您的帮助，和我一起对hana-ui进行移植、升级。
    我的开发计划如下：

#### 移植

移植过程在6-9个月内能顺利完成，同时完成doc站点的发布。

1. 将seed、burgeon、flower组件移植，有些组件移植ng能有更好的解决方案，这里我们可能要舍弃一些组件转用ng的特性来实现。
2. 完善css动效。目前的有些组件动效可能有些僵硬，或者有些缓慢，这部分需要重新设计。

#### 升级

升级过程因为需要讨论一些组件提案以及保证组件质量，可能一个月内新增1-3个组件已经是极限。保守估计6个月完成。

theme方面这个可以乐观一些，三个月出一个theme的可用版本。

1. 补全组件类别。目前还缺少一些标配组件，如栅格，布局……这部分我们需要补全。
2. 新增theme。我的计划是再新增两个theme，以丰富hana品种的多样性。我能感觉出来，您一开始取hana的名字不光是因为hana，更是希望它的theme能像花一样绚烂，因此才会有`himawari`这个名字。

#### 扩展

扩展部分目前距离我们比较遥远，可以在完成移植工作后再思考这一块

1. 新增高级组件。
#### 最后
因为工作的原因，无法把精力全部投入hana，整个开发计划还可能根据实际情况进行调整。不过大体过程就是这样。

**Comment by dtysky** [comment]
你好，这个项目离发布有一段时间了，也基本满足我们的需求，但由于开发时间较早所以肯定有一些和后来的最佳实践落后的地方，这一点确实可能不满足某些需求。

个人对angular的设计也是比较欣赏的，虽然在国内用户不多，但其工程化设计和稳定性都值得赞赏，如果阁下愿意为这个项目做出贡献我们非常欢迎。

开源工程都是一步一步来的，只要有决心最终一定会完成，我的另一系列开源项目sein.js大部分也基本也是我一个人完成的，加油，有什么需要帮助的可以直接留言。
