### ISSUE TITLE
日历组件按上下键操作没有阻止页面滚动

### ISSUE THREAD

**Issue by Justineo** [hana-group/hana-ui#2]
RT.

**Comment by dtysky** [comment]
浏览器版本是？我们测试没有出现这个问题。

**Comment by Justineo** [comment]
> Google Chrome 64 (macOS High Sierra)

看了一下，只有这个会复现：

![image](https://user-images.githubusercontent.com/1726061/36655726-6ecb6606-1aff-11e8-9b7a-1e34fd7913f7.png)

**Comment by dtysky** [comment]
已解决。 #3
